# -*- coding: utf-8 -*-
"""baekjoon_10828_try_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TFIwrPw-3lpOEkfRb8nmwQeY3DvWBvWA
"""

import sys
input = sys.stdin.readline
rep = int(input())
stack = []
for _ in range(rep):
    comend = ''
    inp = 0
    x = list(input().split())
    if len(x) == 2:
        comend, inp = x
    else:
        comend = x[0]
    if comend == 'push':
        stack.append(inp)
    elif comend == 'pop':
        if len(stack) == 0:
            print(-1)
        else:
            print(stack.pop())
    elif comend == 'size':
        print(len(stack))
    elif comend == 'empty':
        if len(stack) == 0:
            print(1)
        else:
            print(0)
    elif comend == 'top':
        if len(stack) > 0:
            print(stack[-1])
        else:
            print(-1)