# -*- coding: utf-8 -*-
"""baekjoon_2164.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4C19hex77cf4n2nwuHr7SYQjqjE143V
"""

from collections import deque
inp = int(input())
que = deque(range(1,(inp+1)))
while len(que) != 1:
    que.popleft()
    x = que.popleft()
    que.append(x)
print(que.pop())